version: "3.8"
services:
  app:
    build:
      context: ./..
      dockerfile: deployments/Dockerfile
    restart: unless-stopped
    stop_signal: SIGINT
    networks:
      - backend
    depends_on:
      - postgres
    ports:
      - "8000:8000"
  postgres:
    image: postgres:14.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/data
    networks:
      - backend
  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./../migrations:/migrations
    networks:
      - backend
    command:
      [ "-path", "/migrations", "-database", "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable", "up" ]
networks:
  backend:
    driver: bridge