server:
  host: localhost
  port: 8000
  shutdown_timeout: 5s
  is_production: false
log:
  level: trace
security:
  password_salt: something
  jwt_secret: amazing
  access_expires_in: 5m
  refresh_expires_in: 720h
postgres:
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  database: postgres